---

- name: Install dependency packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ dependency_packages }}"

#### Install cryptopro
- name: Download and Unarchive cryptopro
  unarchive:
    src: "{{ item }}"
    dest: /tmp
    remote_src: yes
  loop:
    - "{{ url_cprocsp }}"

- name: Install cprocsp
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ cprocsp_packages }}"

#### Install license key cryptopro
#- name: Install license key cprocsp
#  command: "/opt/cprocsp/sbin/amd64/cpconfig -license -set {{ cprocsp_key }}"

- include: install_libphpcades.yml
  when: libphpcades_enabled | default(False)

...